config/routes.rb
Rails.application.routes.draw do
  resources :groups, only: [] do
    resources :users, only: [:index, :show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  broadcasts_refreshes
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :group
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_group

  def index
    sleep 2
    @users = User.all.order(sort_column + ' ' + sort_direction)
  end

  private

  def find_group
    @group = Group.find(params[:group_id])
  end

  def sort_column
    User.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def next_direction(column)
    if params[:sort] == column && params[:direction] == "asc"
      "desc"
    else
      "asc"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Turbo8Stimulus</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield :head %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/users/index.html.erb
<% turbo_refreshes_with method: :morph, scroll: :preserve %>
<%= turbo_stream_from @group %>

<div data-controller="connected"></div>

<table class="min-w-full leading-normal">
  <thead>
    <tr>
      <% ['name', 'email', 'created_at'].each do |column| %>
        <th class="px-5 py-3 bg-gray-600 text-left text-xs font-semibold text-gray-100 uppercase tracking-wider">
          <%= link_to column.titleize, group_users_path(group: @group, sort: column, direction: next_direction(column)) %>
        </th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
          <%= user.name %>
        </td>
        <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
          <%= user.email %>
        </td>
        <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
          <%= user.created_at.strftime("%Y-%m-%d") %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @user %>

    <%= link_to "Edit this user", edit_user_path(@user), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this user", user_path(@user), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to users", users_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>